services:
  app:
    image: node:18-alpine
    container_name: react_01
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./app/:/app
    # command: sh -c "yarn create react-app . && yarn install && yarn start"
    # command: sh -c "yarn install && yarn start"
    command: sh -c "yarn start"